### ISSUE TITLE
Hex color values for the default Tradingview theme (included themes don't match)

### ISSUE THREAD

**Issue by ThoughtPhotography** [salbert11/pinescript#1]
I'm constantly switching back and forth between the Pine Script editor / Cursor (VS Code) and having the exact same color theme would really help.

I find Tradingview's very easy on the eyes, and while Original Dark is close, it's noticeably off. 

An easy way to tell is using something like PowerToys Color Picker which shows the hex value of whatever you hover. Clicking the mouse stores the color in a palette which could be copied into theme file.

Unfortunately, this seems to be a lot harder than it should be, so I thought I'd share the colors (or very close to them) in case there's additional themes in a future update. 
 
color1  = #131722   //main background
color2  = #343843   //text (commented)
color3  = #5b9cf6    //text
color4  = #388e3c   //text (strings)
color5  = #d1d4dc  //text (normal)
color6  = #f57f17    //text (integers)
color7  = #f57b7f    //<-this text
color8  = #132042   //current line background
color9  = #b968c7   //text (imported function)
color10 = #42bba6  //text (operators, commas etc.)
color11 = #f57c00    //underline (ambiguous)
color12 = #f23645   //underline (error)
color13 = #4f5051   //selected text background
color14 = #089950  //local working changes
 
![image](https://github.com/user-attachments/assets/91b1b31b-f183-4709-9014-afb623f4cb4c)

Thanks!

**Comment by salbert11** [comment]
Thank you for the detailed color breakdown! I’ll work on refining the theme colors to better match the default TradingView Dark theme as you've suggested. I’ll incorporate these changes in a future update, so it will be easier on the eyes when switching between the Pine Script editor and VS Code. Your input is very helpful—stay tuned for the update!

**Comment by salbert11** [comment]
Thank you for the detailed color breakdown! I’ll work on refining the theme colors to better match the default TradingView Dark theme as you've suggested. I’ll incorporate these changes in a future update, so it will be easier on the eyes when switching between the Pine Script editor and VS Code. Your input is very helpful—stay tuned for the update!

**Comment by salbert11** [comment]
Good news! A new update has been released, and I’ve included the color adjustments you suggested to better match the default TradingView Dark theme. This should make switching between the Pine Script editor and VS Code a more seamless experience. Thanks again for your input, and enjoy the update!

**Comment by ThoughtPhotography** [comment]
Great,  if I'd discovered I could zoom to the pixel level with ColorPicker I would've been more accurate. ;)
I had to re-download/install to update, but that's a Cursor problem.
